/* Purpose: run every program in kit/corpus.json through the C binding and
 *   print what it answered as JSON, so
 *   extensions/python/tests/ch21_another_language_at_the_seam/test_c_binding.py
 *   can hold the two live seats to the same answers.
 * Assumes: the corpus path arrives as argv[1]; nothing else is read.
 * Guarantees: validates and decodes every JSON string before writing stdout,
 *   then prints one JSON object and exits 0; a malformed string names the
 *   defect on stderr, exits 1 and writes no partial report. A program that
 *   raises is reported as an `error` field rather than ending the run,
 *   because a seat that stopped at the first divergence would hide the rest
 *   [tested: tests/test_kit.py;
 *   commit=da8c4da9df83114ab1d32f3e4049008f37535886].
 * Owns resources: the corpus buffer, decoded source vector and one runtime,
 *   all released before returning.
 * Decides: the report carries each answer's KIND and the engine's own TEXT
 *   rather than a wire form, because this seat has no wire codec (C6 in
 *   ai-cmetta-c-constraints.md). Those two plus the answer COUNT are what the
 *   Python side compares, and between them they pin metatype, spelling and
 *   multiplicity.
 * Open Obligations:
 *   To Do: None
 *   Hacks: None
 *   Future Enhancements: None
 */

#include <cmetta.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* A minimal JSON string writer. Enough for exactly what this report holds:
   engine text, kind names and source. */
static void json_string_n(FILE *out, const char *s, size_t len)
{ fputc('"', out);
  for (size_t i = 0; s && i < len; i++)
  { unsigned char c = (unsigned char)s[i];
    switch ( c )
    { case '"':  fputs("\\\"", out); break;
      case '\\': fputs("\\\\", out); break;
      case '\n': fputs("\\n", out); break;
      case '\r': fputs("\\r", out); break;
      case '\t': fputs("\\t", out); break;
      default:
        if ( c < 0x20 ) fprintf(out, "\\u%04x", c);
        else fputc((int)c, out);
    }
  }
  fputc('"', out);
}

static void json_string(FILE *out, const char *s)
{ json_string_n(out, s, s ? strlen(s) : 0);
}

/* The corpus is read with a scanner rather than a JSON parser, because the
   only thing wanted from it is every "source" value and this file exists to
   test the binding, not to grow a dependency. The corpus is generated by
   nobody and edited by hand, so its shape is stable. */
static char *slurp(const char *path, size_t *length)
{ FILE *f = fopen(path, "rb");
  char *buffer = NULL;
  long size;
  bool read_failed, close_failed;
  if ( !f ) return NULL;
  if ( fseek(f, 0, SEEK_END) != 0 ) goto fail;
  size = ftell(f);
  if ( size < 0 || (uintmax_t)size > SIZE_MAX - 1 ||
       fseek(f, 0, SEEK_SET) != 0 ||
       !(buffer = malloc((size_t)size + 1)) )
    goto fail;
  *length = fread(buffer, 1, (size_t)size, f);
  read_failed = *length != (size_t)size || ferror(f);
  close_failed = fclose(f) != 0;
  if ( read_failed || close_failed )
  { free(buffer);
    return NULL;
  }
  buffer[*length] = '\0';
  return buffer;
fail:
  fclose(f);
  return NULL;
}

typedef struct json_text
{ char *data;
  size_t len;
} json_text;

typedef struct source_list
{ json_text *items;
  size_t len, cap;
} source_list;

static int hex_digit(unsigned char c)
{ if ( c >= '0' && c <= '9' ) return c - '0';
  if ( c >= 'a' && c <= 'f' ) return c - 'a' + 10;
  if ( c >= 'A' && c <= 'F' ) return c - 'A' + 10;
  return -1;
}

static bool read_hex4(const unsigned char **cursor, const unsigned char *end,
                      unsigned int *value)
{ unsigned int out = 0;
  size_t i;

  if ( (size_t)(end - *cursor) < 4 ) return false;
  for (i = 0; i < 4; i++)
  { int digit = hex_digit((*cursor)[i]);
    if ( digit < 0 ) return false;
    out = out * 16u + (unsigned int)digit;
  }
  *cursor += 4;
  *value = out;
  return true;
}

static size_t put_utf8(char *out, unsigned int code)
{ if ( code < 0x80 )
  { out[0] = (char)code;
    return 1;
  }
  if ( code < 0x800 )
  { out[0] = (char)(0xc0u | (code >> 6));
    out[1] = (char)(0x80u | (code & 0x3fu));
    return 2;
  }
  if ( code < 0x10000 )
  { out[0] = (char)(0xe0u | (code >> 12));
    out[1] = (char)(0x80u | ((code >> 6) & 0x3fu));
    out[2] = (char)(0x80u | (code & 0x3fu));
    return 3;
  }
  out[0] = (char)(0xf0u | (code >> 18));
  out[1] = (char)(0x80u | ((code >> 12) & 0x3fu));
  out[2] = (char)(0x80u | ((code >> 6) & 0x3fu));
  out[3] = (char)(0x80u | (code & 0x3fu));
  return 4;
}

/* This is the same bounded escape and surrogate-pair algorithm as the
   engine's fast JSON reader, adapted to return owned C text rather than an
   SWI term [source: engine/json_codec.c, read_string;
   commit=da8c4da9df83114ab1d32f3e4049008f37535886]. */
static bool read_json_string(const unsigned char **cursor,
                             const unsigned char *end, json_text *out,
                             const char **reason)
{ const unsigned char *p = *cursor;
  size_t capacity = (size_t)(end - p);
  char *data;
  size_t n = 0;

  if ( capacity == SIZE_MAX || !(data = malloc(capacity + 1)) )
  { *reason = "out of memory decoding a JSON string";
    return false;
  }
  while ( p < end )
  { unsigned char c = *p++;
    if ( c == '"' )
    { data[n] = '\0';
      out->data = data;
      out->len = n;
      *cursor = p;
      return true;
    }
    if ( c < 0x20 )
    { *reason = "unescaped control byte in JSON string";
      goto fail;
    }
    if ( c != '\\' )
    { data[n++] = (char)c;
      continue;
    }
    if ( p == end )
    { *reason = "unterminated escape in JSON string";
      goto fail;
    }
    c = *p++;
    switch ( c )
    { case '"': data[n++] = '"'; break;
      case '\\': data[n++] = '\\'; break;
      case '/': data[n++] = '/'; break;
      case 'b': data[n++] = '\b'; break;
      case 'f': data[n++] = '\f'; break;
      case 'n': data[n++] = '\n'; break;
      case 'r': data[n++] = '\r'; break;
      case 't': data[n++] = '\t'; break;
      case 'u':
      { unsigned int code;
        if ( !read_hex4(&p, end, &code) )
        { *reason = "invalid Unicode escape in JSON string";
          goto fail;
        }
        if ( code >= 0xd800 && code < 0xdc00 )
        { unsigned int low;
          if ( (size_t)(end - p) < 2 || p[0] != '\\' || p[1] != 'u' )
          { *reason = "high surrogate without a low surrogate";
            goto fail;
          }
          p += 2;
          if ( !read_hex4(&p, end, &low) ||
               low < 0xdc00 || low >= 0xe000 )
          { *reason = "invalid low surrogate in JSON string";
            goto fail;
          }
          code = (code - 0xd800) * 0x400u + (low - 0xdc00) + 0x10000u;
        } else if ( code >= 0xdc00 && code < 0xe000 )
        { *reason = "lone low surrogate in JSON string";
          goto fail;
        }
        n += put_utf8(data + n, code);
        break;
      }
      default:
        *reason = "invalid escape in JSON string";
        goto fail;
    }
  }
  *reason = "unterminated JSON string";
fail:
  free(data);
  return false;
}

static const unsigned char *skip_json_space(const unsigned char *p,
                                             const unsigned char *end)
{ while ( p < end && (*p == ' ' || *p == '\t' ||
                       *p == '\n' || *p == '\r') )
    p++;
  return p;
}

static bool source_push(source_list *sources, json_text source)
{ if ( sources->len == sources->cap )
  { size_t cap = sources->cap ? sources->cap * 2 : 8;
    json_text *grown;
    if ( cap < sources->cap || cap > SIZE_MAX / sizeof(*grown) ) return false;
    grown = realloc(sources->items, cap * sizeof(*grown));
    if ( !grown ) return false;
    sources->items = grown;
    sources->cap = cap;
  }
  sources->items[sources->len++] = source;
  return true;
}

static void sources_free(source_list *sources)
{ size_t i;
  for (i = 0; i < sources->len; i++) free(sources->items[i].data);
  free(sources->items);
}

/* Decode the whole lexical string stream before stdout begins. A malformed
   late source therefore cannot leave a syntactically valid-looking prefix. */
static bool collect_sources(const char *corpus, size_t length,
                            source_list *sources, const char **reason)
{ const unsigned char *p = (const unsigned char *)corpus;
  const unsigned char *end = p + length;

  while ( p < end )
  { json_text key = {0};
    const unsigned char *after;
    if ( *p++ != '"' ) continue;
    if ( !read_json_string(&p, end, &key, reason) ) return false;
    after = skip_json_space(p, end);
    if ( key.len == 6 && memcmp(key.data, "source", 6) == 0 &&
         after < end && *after == ':' )
    { json_text source = {0};
      after = skip_json_space(after + 1, end);
      if ( after == end || *after != '"' )
      { free(key.data);
        *reason = "a source value is not a JSON string";
        return false;
      }
      p = after + 1;
      if ( !read_json_string(&p, end, &source, reason) )
      { free(key.data);
        return false;
      }
      if ( memchr(source.data, '\0', source.len) )
      { free(key.data);
        free(source.data);
        *reason = "a source contains NUL, which mt_run cannot represent";
        return false;
      }
      if ( !source_push(sources, source) )
      { free(key.data);
        free(source.data);
        *reason = "out of memory collecting corpus sources";
        return false;
      }
    }
    free(key.data);
  }
  return true;
}

int main(int argc, char **argv)
{ metta *m;
  char *corpus;
  size_t length = 0;
  source_list sources = {0};
  const char *reason = NULL;
  size_t program;
  int first_program = 1;

  if ( argc < 2 )
  { fprintf(stderr, "usage: driver <corpus.json>\n");
    return 1;
  }
  if ( !(corpus = slurp(argv[1], &length)) )
  { fprintf(stderr, "cannot read %s\n", argv[1]);
    return 1;
  }
  if ( !collect_sources(corpus, length, &sources, &reason) )
  { fprintf(stderr, "invalid corpus: %s\n", reason ? reason : "unknown error");
    free(corpus);
    sources_free(&sources);
    return 1;
  }
  if ( !(m = mt_open(NULL)) )
  { fprintf(stderr, "boot: %s\n", mt_errmsg());
    free(corpus);
    sources_free(&sources);
    return 1;
  }

  printf("{\"programs\":[");
  for (program = 0; program < sources.len; program++)
  { const json_text *source = &sources.items[program];
    mt_answers *answers;
    const mt_row *row;
    int first_answer = 1;

    if ( !first_program ) printf(",");
    first_program = 0;
    printf("{\"source\":");
    json_string_n(stdout, source->data, source->len);

    mt_clear();
    answers = mt_run(m, source->data);
    if ( !answers )
    { printf(",\"error\":");
      json_string(stdout, mt_errmsg() ? mt_errmsg() : "unknown");
      printf("}");
      mt_answers_free(answers);
      continue;
    }

    printf(",\"answers\":[");
    /* The row form, because this report wants the group and the engine's own
       text beside each answer, not the answer alone. */
    while ( (row = mt_row_next(answers)) != NULL )
    {
      if ( !first_answer ) printf(",");
      first_answer = 0;
      printf("{\"group\":%zu,\"kind\":", row->group);
      json_string(stdout, mt_kind_str(mt_kind_of(row->atom)));
      printf(",\"text\":");
      json_string(stdout, row->text);
      printf("}");
    }
    printf("]}");
    mt_answers_free(answers);
  }
  printf("]}\n");

  free(corpus);
  sources_free(&sources);
  mt_close(m);
  return 0;
}
