/* Purpose: run every program in kit/corpus.json through the C binding and
 *   print what it answered as JSON, so
 *   extensions/python/tests/ch21_another_language_at_the_seam/test_c_binding.py
 *   can hold the two live seats to the same answers.
 * Assumes: the corpus path arrives as argv[1]; nothing else is read.
 * Guarantees: prints one JSON object on stdout and exits 0, or names the
 *   failure on stderr and exits 1. A program that raises is reported as an
 *   `error` field rather than ending the run, because a seat that stopped at
 *   the first divergence would hide the rest.
 * Owns: one runtime, closed before returning.
 * Decides: the report carries each answer's KIND and the engine's own TEXT
 *   rather than a wire form, because this seat has no wire codec (C6 in
 *   ai-cetta-c-constraints.md). Those two plus the answer COUNT are what the
 *   Python side compares, and between them they pin metatype, spelling and
 *   multiplicity.
 * Open Obligations:
 *   To Do: None
 *   Hacks: None
 *   Future Enhancements: None
 */

#include <cetta.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* A minimal JSON string writer. Enough for exactly what this report holds:
   engine text, kind names and source. */
static void json_string(FILE *out, const char *s)
{ fputc('"', out);
  for (; s && *s; s++)
  { unsigned char c = (unsigned char)*s;
    switch ( c )
    { case '"':  fputs("\\\"", out); break;
      case '\\': fputs("\\\\", out); break;
      case '\n': fputs("\\n", out); break;
      case '\r': fputs("\\r", out); break;
      case '\t': fputs("\\t", out); break;
      default:
        if ( c < 0x20 ) fprintf(out, "\\u%04x", c);
        else fputc((int)c, out);
    }
  }
  fputc('"', out);
}

/* The corpus is read with a scanner rather than a JSON parser, because the
   only thing wanted from it is every "source" value and this file exists to
   test the binding, not to grow a dependency. The corpus is generated by
   nobody and edited by hand, so its shape is stable. */
static char *slurp(const char *path, size_t *length)
{ FILE *f = fopen(path, "rb");
  char *buffer;
  long size;
  if ( !f ) return NULL;
  fseek(f, 0, SEEK_END);
  size = ftell(f);
  fseek(f, 0, SEEK_SET);
  if ( size < 0 || !(buffer = malloc((size_t)size + 1)) ) { fclose(f); return NULL; }
  *length = fread(buffer, 1, (size_t)size, f);
  buffer[*length] = '\0';
  fclose(f);
  return buffer;
}

/* Unescape one JSON string value in place, starting just after its opening
   quote. Returns the character after the closing quote, or NULL. */
static const char *read_json_string(const char *p, char *out, size_t cap)
{ size_t n = 0;
  for (; *p && *p != '"'; p++)
  { char c = *p;
    if ( c == '\\' )
    { p++;
      switch ( *p )
      { case 'n': c = '\n'; break;
        case 't': c = '\t'; break;
        case 'r': c = '\r'; break;
        case '"': c = '"';  break;
        case '\\': c = '\\'; break;
        default: c = *p;
      }
    }
    if ( n + 1 < cap ) out[n++] = c;
  }
  out[n] = '\0';
  return *p == '"' ? p + 1 : NULL;
}

int main(int argc, char **argv)
{ cetta *m;
  char *corpus;
  size_t length = 0;
  const char *p;
  int first_program = 1;

  if ( argc < 2 )
  { fprintf(stderr, "usage: driver <corpus.json>\n");
    return 1;
  }
  if ( !(corpus = slurp(argv[1], &length)) )
  { fprintf(stderr, "cannot read %s\n", argv[1]);
    return 1;
  }
  if ( !(m = cetta_open(NULL)) )
  { fprintf(stderr, "boot: %s\n", cetta_errmsg());
    return 1;
  }

  printf("{\"programs\":[");
  for (p = corpus; (p = strstr(p, "\"source\"")) != NULL; )
  { static char source[4096];
    cetta_answers *answers;
    const cetta_atom *atom;
    int first_answer = 1;

    p = strchr(p + 8, '"');
    if ( !p ) break;
    if ( !(p = read_json_string(p + 1, source, sizeof(source))) ) break;

    if ( !first_program ) printf(",");
    first_program = 0;
    printf("{\"source\":");
    json_string(stdout, source);

    cetta_clear();
    answers = cetta_run(m, source);
    if ( !answers )
    { printf(",\"error\":");
      json_string(stdout, cetta_errmsg() ? cetta_errmsg() : "unknown");
      printf("}");
      cetta_answers_free(answers);
      continue;
    }

    printf(",\"answers\":[");
    while ( (atom = cetta_next(answers)) != NULL )
    {
      if ( !first_answer ) printf(",");
      first_answer = 0;
      printf("{\"group\":%zu,\"kind\":", cetta_group(answers));
      json_string(stdout, cetta_kind_str(cetta_kind_of(atom)));
      printf(",\"text\":");
      json_string(stdout, cetta_answer_text(answers));
      printf("}");
    }
    printf("]}");
    cetta_answers_free(answers);
  }
  printf("]}\n");

  free(corpus);
  cetta_close(m);
  return 0;
}
